project_id = "ifpidxsvlawqsacrclmr"
[functions.update_meal_session_statuses]
enabled = true
verify_jwt = false
import_map = "./functions/update_meal_session_statuses/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update_meal_session_statuses/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update_meal_session_statuses/*.html" ]

[functions.validate_identity]
enabled = true
verify_jwt = false
import_map = "./functions/validate_identity/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/validate_identity/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/validate_identity/*.html" ]
