/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProcurementVendorsRouteImport } from './routes/procurement-vendors'
import { Route as ProcurementPosRouteImport } from './routes/procurement-pos'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MemberPassRouteImport } from './routes/member-pass'
import { Route as MealSummaryRouteImport } from './routes/meal-summary'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as GuestMealsRouteImport } from './routes/guest-meals'
import { Route as ExpenseRouteImport } from './routes/expense'
import { Route as DevToolsRouteImport } from './routes/dev-tools'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcurementVendorsIndexRouteImport } from './routes/procurement-vendors.index'
import { Route as ProcurementPosIndexRouteImport } from './routes/procurement-pos.index'
import { Route as ProcurementVendorsVendorIdRouteImport } from './routes/procurement-vendors.$vendorId'
import { Route as ProcurementPosPoIdRouteImport } from './routes/procurement-pos.$poId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementVendorsRoute = ProcurementVendorsRouteImport.update({
  id: '/procurement-vendors',
  path: '/procurement-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementPosRoute = ProcurementPosRouteImport.update({
  id: '/procurement-pos',
  path: '/procurement-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberPassRoute = MemberPassRouteImport.update({
  id: '/member-pass',
  path: '/member-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const MealSummaryRoute = MealSummaryRouteImport.update({
  id: '/meal-summary',
  path: '/meal-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestMealsRoute = GuestMealsRouteImport.update({
  id: '/guest-meals',
  path: '/guest-meals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseRoute = ExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsRoute = DevToolsRouteImport.update({
  id: '/dev-tools',
  path: '/dev-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementVendorsIndexRoute = ProcurementVendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcurementVendorsRoute,
} as any)
const ProcurementPosIndexRoute = ProcurementPosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcurementPosRoute,
} as any)
const ProcurementVendorsVendorIdRoute =
  ProcurementVendorsVendorIdRouteImport.update({
    id: '/$vendorId',
    path: '/$vendorId',
    getParentRoute: () => ProcurementVendorsRoute,
  } as any)
const ProcurementPosPoIdRoute = ProcurementPosPoIdRouteImport.update({
  id: '/$poId',
  path: '/$poId',
  getParentRoute: () => ProcurementPosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/backup': typeof BackupRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/dev-tools': typeof DevToolsRoute
  '/expense': typeof ExpenseRoute
  '/guest-meals': typeof GuestMealsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/meal-summary': typeof MealSummaryRoute
  '/member-pass': typeof MemberPassRoute
  '/members': typeof MembersRoute
  '/procurement': typeof ProcurementRoute
  '/procurement-pos': typeof ProcurementPosRouteWithChildren
  '/procurement-vendors': typeof ProcurementVendorsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/procurement-pos/$poId': typeof ProcurementPosPoIdRoute
  '/procurement-vendors/$vendorId': typeof ProcurementVendorsVendorIdRoute
  '/procurement-pos/': typeof ProcurementPosIndexRoute
  '/procurement-vendors/': typeof ProcurementVendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/backup': typeof BackupRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/dev-tools': typeof DevToolsRoute
  '/expense': typeof ExpenseRoute
  '/guest-meals': typeof GuestMealsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/meal-summary': typeof MealSummaryRoute
  '/member-pass': typeof MemberPassRoute
  '/members': typeof MembersRoute
  '/procurement': typeof ProcurementRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/procurement-pos/$poId': typeof ProcurementPosPoIdRoute
  '/procurement-vendors/$vendorId': typeof ProcurementVendorsVendorIdRoute
  '/procurement-pos': typeof ProcurementPosIndexRoute
  '/procurement-vendors': typeof ProcurementVendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/backup': typeof BackupRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/dev-tools': typeof DevToolsRoute
  '/expense': typeof ExpenseRoute
  '/guest-meals': typeof GuestMealsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/meal-summary': typeof MealSummaryRoute
  '/member-pass': typeof MemberPassRoute
  '/members': typeof MembersRoute
  '/procurement': typeof ProcurementRoute
  '/procurement-pos': typeof ProcurementPosRouteWithChildren
  '/procurement-vendors': typeof ProcurementVendorsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/procurement-pos/$poId': typeof ProcurementPosPoIdRoute
  '/procurement-vendors/$vendorId': typeof ProcurementVendorsVendorIdRoute
  '/procurement-pos/': typeof ProcurementPosIndexRoute
  '/procurement-vendors/': typeof ProcurementVendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/backup'
    | '/billing'
    | '/dashboard'
    | '/dev-tools'
    | '/expense'
    | '/guest-meals'
    | '/inventory'
    | '/login'
    | '/meal-summary'
    | '/member-pass'
    | '/members'
    | '/procurement'
    | '/procurement-pos'
    | '/procurement-vendors'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/procurement-pos/$poId'
    | '/procurement-vendors/$vendorId'
    | '/procurement-pos/'
    | '/procurement-vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/backup'
    | '/billing'
    | '/dashboard'
    | '/dev-tools'
    | '/expense'
    | '/guest-meals'
    | '/inventory'
    | '/login'
    | '/meal-summary'
    | '/member-pass'
    | '/members'
    | '/procurement'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/procurement-pos/$poId'
    | '/procurement-vendors/$vendorId'
    | '/procurement-pos'
    | '/procurement-vendors'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/backup'
    | '/billing'
    | '/dashboard'
    | '/dev-tools'
    | '/expense'
    | '/guest-meals'
    | '/inventory'
    | '/login'
    | '/meal-summary'
    | '/member-pass'
    | '/members'
    | '/procurement'
    | '/procurement-pos'
    | '/procurement-vendors'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/procurement-pos/$poId'
    | '/procurement-vendors/$vendorId'
    | '/procurement-pos/'
    | '/procurement-vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  BackupRoute: typeof BackupRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  DevToolsRoute: typeof DevToolsRoute
  ExpenseRoute: typeof ExpenseRoute
  GuestMealsRoute: typeof GuestMealsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MealSummaryRoute: typeof MealSummaryRoute
  MemberPassRoute: typeof MemberPassRoute
  MembersRoute: typeof MembersRoute
  ProcurementRoute: typeof ProcurementRoute
  ProcurementPosRoute: typeof ProcurementPosRouteWithChildren
  ProcurementVendorsRoute: typeof ProcurementVendorsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement-vendors': {
      id: '/procurement-vendors'
      path: '/procurement-vendors'
      fullPath: '/procurement-vendors'
      preLoaderRoute: typeof ProcurementVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement-pos': {
      id: '/procurement-pos'
      path: '/procurement-pos'
      fullPath: '/procurement-pos'
      preLoaderRoute: typeof ProcurementPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-pass': {
      id: '/member-pass'
      path: '/member-pass'
      fullPath: '/member-pass'
      preLoaderRoute: typeof MemberPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-summary': {
      id: '/meal-summary'
      path: '/meal-summary'
      fullPath: '/meal-summary'
      preLoaderRoute: typeof MealSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-meals': {
      id: '/guest-meals'
      path: '/guest-meals'
      fullPath: '/guest-meals'
      preLoaderRoute: typeof GuestMealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense': {
      id: '/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools': {
      id: '/dev-tools'
      path: '/dev-tools'
      fullPath: '/dev-tools'
      preLoaderRoute: typeof DevToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement-vendors/': {
      id: '/procurement-vendors/'
      path: '/'
      fullPath: '/procurement-vendors/'
      preLoaderRoute: typeof ProcurementVendorsIndexRouteImport
      parentRoute: typeof ProcurementVendorsRoute
    }
    '/procurement-pos/': {
      id: '/procurement-pos/'
      path: '/'
      fullPath: '/procurement-pos/'
      preLoaderRoute: typeof ProcurementPosIndexRouteImport
      parentRoute: typeof ProcurementPosRoute
    }
    '/procurement-vendors/$vendorId': {
      id: '/procurement-vendors/$vendorId'
      path: '/$vendorId'
      fullPath: '/procurement-vendors/$vendorId'
      preLoaderRoute: typeof ProcurementVendorsVendorIdRouteImport
      parentRoute: typeof ProcurementVendorsRoute
    }
    '/procurement-pos/$poId': {
      id: '/procurement-pos/$poId'
      path: '/$poId'
      fullPath: '/procurement-pos/$poId'
      preLoaderRoute: typeof ProcurementPosPoIdRouteImport
      parentRoute: typeof ProcurementPosRoute
    }
  }
}

interface ProcurementPosRouteChildren {
  ProcurementPosPoIdRoute: typeof ProcurementPosPoIdRoute
  ProcurementPosIndexRoute: typeof ProcurementPosIndexRoute
}

const ProcurementPosRouteChildren: ProcurementPosRouteChildren = {
  ProcurementPosPoIdRoute: ProcurementPosPoIdRoute,
  ProcurementPosIndexRoute: ProcurementPosIndexRoute,
}

const ProcurementPosRouteWithChildren = ProcurementPosRoute._addFileChildren(
  ProcurementPosRouteChildren,
)

interface ProcurementVendorsRouteChildren {
  ProcurementVendorsVendorIdRoute: typeof ProcurementVendorsVendorIdRoute
  ProcurementVendorsIndexRoute: typeof ProcurementVendorsIndexRoute
}

const ProcurementVendorsRouteChildren: ProcurementVendorsRouteChildren = {
  ProcurementVendorsVendorIdRoute: ProcurementVendorsVendorIdRoute,
  ProcurementVendorsIndexRoute: ProcurementVendorsIndexRoute,
}

const ProcurementVendorsRouteWithChildren =
  ProcurementVendorsRoute._addFileChildren(ProcurementVendorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  BackupRoute: BackupRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  DevToolsRoute: DevToolsRoute,
  ExpenseRoute: ExpenseRoute,
  GuestMealsRoute: GuestMealsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MealSummaryRoute: MealSummaryRoute,
  MemberPassRoute: MemberPassRoute,
  MembersRoute: MembersRoute,
  ProcurementRoute: ProcurementRoute,
  ProcurementPosRoute: ProcurementPosRouteWithChildren,
  ProcurementVendorsRoute: ProcurementVendorsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
